# Name of your site (displayed in the header)
name: Ray Tsai

# Short bio or description (displayed in the header)
description: Developer / Architect / Creator

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/4031732?v=3&s=460

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: connect@mingjuitsai.com
  github: mingjuitsai
  linkedin: mingraytsai
  codepen: https://codepen.io/raytsai/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://mingjuitsai.com
host: 127.0.0.1
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v4.4.1

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  # style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap
  - jekyll-minifier

jekyll-minifier:
  preserve_php: true
  remove_comments: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_javascript: true
  compress_json: true
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_javascript_protocol: false
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: false
  simple_boolean_attributes: false
  compress_js_templates: false
  preserve_patterns: []
  uglifier_args:
    harmony: true

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
